### ISSUE TITLE
Is it possible to host the web ui in my local machine ?

### ISSUE THREAD

**Issue by hikerpig** [smelukov/statoscope#30]
I think it would be better to include a demo folder in the source code, and a script like `npm run start-demo` to run web application locally. Because people may have concerns of uploading sensitive project stats data.

I dug into the codebase and found my way of creating an 'index.html' file and call `Statoscope.default(data)` (yep without webpack).

**Comment by smelukov** [comment]
Hi! Yep, In the near release, I plan to implement a webpack plugin to start Statoscope locally

**Comment by hikerpig** [comment]
Nice move 🙌. I am picturing something like `webpack-bundle-analyzer` that gernates a report html and open it automatically. Just my two cents.
Looking forward to it.

**Comment by smelukov** [comment]
👍🏻

**Comment by smelukov** [comment]
Solved in [3.2.0](https://github.com/smelukov/statoscope/blob/master/packages/ui-webpack/CHANGELOG.md#320-11-december-2020)

**Comment by budarin** [comment]
@smelukov 

the error is still present
```js
class l {
        constructor(e) {
            this.readers = e.map(e=>{
                const t = new s(e);
                return t.eventProgress.on((e,{total: t, loaded: n, chunkSize: r})=>{
                    this.loadedBytes += r,
                    this.eventProgress.emit(this, {
                        total: this.totalBytes,
                        loaded: this.loadedBytes
                    })
                }
                ),
                t
            }
            ),
            this.totalBytes = e.reduce((e,t)=>e + t.size, 0),
            this.loadedBytes = 0,
            this.eventProgress = new o.a
        }
```
`e` is FileList so it doesn't have `map` property

**Comment by smelukov** [comment]
@budarin are you about [this](https://github.com/smelukov/statoscope/issues/29) issue?

**Comment by budarin** [comment]
Yes, I mixed up the issue :)
